# Generated by Django 3.2.7 on 2021-09-14 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(default='', max_length=200, verbose_name='分类'),
            preserve_default=False,
        ),
    ]
