# Generated by Django 3.2.7 on 2021-10-25 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articles_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='outline',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='概要'),
            preserve_default=False,
        ),
    ]
